spring.jpa.open-in-view=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=37dc9cfd6c69bf5c2d1545be270762f230bd8fd2556e0dcb16ae45554bdaabbe1c39228764a49ca88023c9dea190f1d4132d997bc667975b44d45fcaf6dd47f6

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.zdroba=DEBUG
logging.level.org.hibernate.SQL=DEBUG