plugins {
    id 'java'
    id 'application'
}

group = 'org.zdroba'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


dependencies {
    // Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation("org.apache.logging.log4j:log4j-api:2.24.3")
    implementation("org.apache.logging.log4j:log4j-core:2.24.3")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.24.3")
// Source: https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    runtimeOnly("org.xerial:sqlite-jdbc:3.50.3.0")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'org.zdroba.MainBD'
    applicationDefaultJvmArgs = ["--enable-native-access=ALL-UNNAMED"]
}
test {
    useJUnitPlatform()
}

tasks.withType(JavaExec).configureEach {
    jvmArgs += "--enable-native-access=ALL-UNNAMED"
}