CREATE TABLE IF NOT EXISTS racers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cnp VARCHAR(50) NOT NULL,
    engine INT NOT NULL,
    team VARCHAR(100) NOT NULL
    );