-- Drop transformation tables first
DROP TABLE IF EXISTS TrailMaintenanceLogs CASCADE;
DROP TABLE IF EXISTS Legaturi_Eliminate CASCADE;

-- Drop original tables
DROP TABLE IF EXISTS TrailFacilities CASCADE;
DROP TABLE IF EXISTS Facilities CASCADE;

DROP TABLE IF EXISTS TrailHazards CASCADE;
DROP TABLE IF EXISTS Hazards CASCADE;

DROP TABLE IF EXISTS TrailTags CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;

DROP TABLE IF EXISTS ElevationPoints CASCADE;
DROP TABLE IF EXISTS Conditions CASCADE;
DROP TABLE IF EXISTS MaintenanceLogs CASCADE;
DROP TABLE IF EXISTS Photos CASCADE;
DROP TABLE IF EXISTS Checkpoints CASCADE;
DROP TABLE IF EXISTS Trail CASCADE;
DROP TABLE IF EXISTS Parks CASCADE;
